services:
  web:
    build: .
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mariadb

  # MariaDB Service
  mariadb:
    image: mariadb:10
    container_name: "${CONTAINER_NAME}"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/mysql/sql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
    environment:
      MARIADB_USER: ${DB_USERNAME}
      #MYSQL_ROOT_HOST:
      MYSQL_DATABASE: ${DB_DATABASE}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      # Adminer Service
  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-8080}:8080"
